### ISSUE TITLE
PhantomJS SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/slush-marklogic-node#526]
phantomjs-prebuilt@2.1.16 was released half a day ago, CI builds started complaining as it runs on an older Node version.

```
phantomjs-prebuilt@2.1.16 install <http://van-ci.demo.marklogic.com/job/Monitor%20for%20slush-marklogic-node%20map%20theme%20build/ws/slush-map/node_modules/phantomjs-prebuilt>
node install.js


<http://van-ci.demo.marklogic.com/job/Monitor%20for%20slush-marklogic-node%20map%20theme%20build/ws/slush-map/node_modules/phantomjs-prebuilt/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js>:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (<http://van-ci.demo.marklogic.com/job/Monitor%20for%20slush-marklogic-node%20map%20theme%20build/ws/slush-map/node_modules/phantomjs-prebuilt/node_modules/request/node_modules/hawk/lib/index.js>:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by grtjn** [comment]
Need to fix for continuity, pinning down on phantomjs-prebuilt@2.1.15 for the time being..
